# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20160229024347) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "generators", force: true do |t|
    t.float    "event1_mean"
    t.float    "event1_variance"
    t.float    "event2_mean"
    t.float    "event2_variance"
    t.float    "event3_mean"
    t.float    "event3_variance"
    t.float    "event4_mean"
    t.float    "event4_variance"
    t.float    "event5_mean"
    t.float    "event5_variance"
    t.float    "event6_mean"
    t.float    "event6_variance"
    t.float    "event7_mean"
    t.float    "event7_variance"
    t.float    "event8_mean"
    t.float    "event8_variance"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.float    "event1_negative_variance"
    t.float    "event1_negative_mean"
    t.float    "event2_negative_mean"
    t.float    "event2_negative_variance"
    t.float    "event3_negative_mean"
    t.float    "event3_negative_variance"
    t.float    "event4_negative_mean"
    t.float    "event4_negative_variance"
    t.float    "event5_negative_mean"
    t.float    "event5_negative_variance"
    t.float    "event6_negative_mean"
    t.float    "event6_negative_variance"
    t.float    "event7_negative_mean"
    t.float    "event7_negative_variance"
    t.float    "event8_negative_mean"
    t.float    "event8_negative_variance"
    t.boolean  "score_8_label"
    t.boolean  "score_1_label"
    t.boolean  "score_2_label"
    t.boolean  "score_3_label"
    t.boolean  "score_4_label"
    t.boolean  "score_5_label"
    t.boolean  "score_6_label"
    t.boolean  "score_7_label"
    t.integer  "score_1_event_1"
    t.integer  "score_1_event_2"
    t.integer  "score_1_event_3"
    t.integer  "score_1_event_4"
    t.integer  "score_1_event_5"
    t.integer  "score_1_event_6"
    t.integer  "score_1_event_7"
    t.integer  "score_1_event_8"
    t.integer  "score_2_event_1"
    t.integer  "score_2_event_2"
    t.integer  "score_2_event_3"
    t.integer  "score_2_event_4"
    t.integer  "score_2_event_5"
    t.integer  "score_2_event_6"
    t.integer  "score_2_event_7"
    t.integer  "score_2_event_8"
    t.integer  "score_3_event_1"
    t.integer  "score_3_event_2"
    t.integer  "score_3_event_3"
    t.integer  "score_3_event_4"
    t.integer  "score_3_event_5"
    t.integer  "score_3_event_6"
    t.integer  "score_3_event_7"
    t.integer  "score_3_event_8"
    t.integer  "score_4_event_1"
    t.integer  "score_4_event_2"
    t.integer  "score_4_event_3"
    t.integer  "score_4_event_4"
    t.integer  "score_4_event_5"
    t.integer  "score_4_event_6"
    t.integer  "score_4_event_7"
    t.integer  "score_4_event_8"
    t.integer  "score_5_event_1"
    t.integer  "score_5_event_2"
    t.integer  "score_5_event_3"
    t.integer  "score_5_event_4"
    t.integer  "score_5_event_5"
    t.integer  "score_5_event_6"
    t.integer  "score_5_event_7"
    t.integer  "score_5_event_8"
    t.integer  "score_6_event_1"
    t.integer  "score_6_event_2"
    t.integer  "score_6_event_3"
    t.integer  "score_6_event_4"
    t.integer  "score_6_event_5"
    t.integer  "score_6_event_6"
    t.integer  "score_6_event_7"
    t.integer  "score_6_event_8"
    t.integer  "score_7_event_1"
    t.integer  "score_7_event_2"
    t.integer  "score_7_event_3"
    t.integer  "score_7_event_4"
    t.integer  "score_7_event_5"
    t.integer  "score_7_event_6"
    t.integer  "score_7_event_7"
    t.integer  "score_7_event_8"
    t.integer  "score_8_event_1"
    t.integer  "score_8_event_2"
    t.integer  "score_8_event_3"
    t.integer  "score_8_event_4"
    t.integer  "score_8_event_5"
    t.integer  "score_8_event_6"
    t.integer  "score_8_event_7"
    t.integer  "score_8_event_8"
  end

  create_table "scores", force: true do |t|
    t.string   "event1"
    t.float    "event1_duration"
    t.string   "event2"
    t.float    "event2_duration"
    t.string   "event3"
    t.float    "event3_duration"
    t.string   "event4"
    t.float    "event4_duration"
    t.string   "event5"
    t.float    "event5_duration"
    t.string   "event6"
    t.float    "event6_duration"
    t.string   "event7"
    t.float    "event7_duration"
    t.string   "event8"
    t.float    "event8_duration"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "generator_id"
  end

end
