class AddTrainingDataToGenerators < ActiveRecord::Migration
  def change
    add_column :generators, :score_1_event_1, :integer
    add_column :generators, :score_1_event_2, :integer
    add_column :generators, :score_1_event_3, :integer
    add_column :generators, :score_1_event_4, :integer
    add_column :generators, :score_1_event_5, :integer
    add_column :generators, :score_1_event_6, :integer
    add_column :generators, :score_1_event_7, :integer
    add_column :generators, :score_1_event_8, :integer
    add_column :generators, :score_2_event_1, :integer
    add_column :generators, :score_2_event_2, :integer
    add_column :generators, :score_2_event_3, :integer
    add_column :generators, :score_2_event_4, :integer
    add_column :generators, :score_2_event_5, :integer
    add_column :generators, :score_2_event_6, :integer
    add_column :generators, :score_2_event_7, :integer
    add_column :generators, :score_2_event_8, :integer
    add_column :generators, :score_3_event_1, :integer
    add_column :generators, :score_3_event_2, :integer
    add_column :generators, :score_3_event_3, :integer
    add_column :generators, :score_3_event_4, :integer
    add_column :generators, :score_3_event_5, :integer
    add_column :generators, :score_3_event_6, :integer
    add_column :generators, :score_3_event_7, :integer
    add_column :generators, :score_3_event_8, :integer
    add_column :generators, :score_4_event_1, :integer
    add_column :generators, :score_4_event_2, :integer
    add_column :generators, :score_4_event_3, :integer
    add_column :generators, :score_4_event_4, :integer
    add_column :generators, :score_4_event_5, :integer
    add_column :generators, :score_4_event_6, :integer
    add_column :generators, :score_4_event_7, :integer
    add_column :generators, :score_4_event_8, :integer
    add_column :generators, :score_5_event_1, :integer
    add_column :generators, :score_5_event_2, :integer
    add_column :generators, :score_5_event_3, :integer
    add_column :generators, :score_5_event_4, :integer
    add_column :generators, :score_5_event_5, :integer
    add_column :generators, :score_5_event_6, :integer
    add_column :generators, :score_5_event_7, :integer
    add_column :generators, :score_5_event_8, :integer
    add_column :generators, :score_6_event_1, :integer
    add_column :generators, :score_6_event_2, :integer
    add_column :generators, :score_6_event_3, :integer
    add_column :generators, :score_6_event_4, :integer
    add_column :generators, :score_6_event_5, :integer
    add_column :generators, :score_6_event_6, :integer
    add_column :generators, :score_6_event_7, :integer
    add_column :generators, :score_6_event_8, :integer
    add_column :generators, :score_7_event_1, :integer
    add_column :generators, :score_7_event_2, :integer
    add_column :generators, :score_7_event_3, :integer
    add_column :generators, :score_7_event_4, :integer
    add_column :generators, :score_7_event_5, :integer
    add_column :generators, :score_7_event_6, :integer
    add_column :generators, :score_7_event_7, :integer
    add_column :generators, :score_7_event_8, :integer
    add_column :generators, :score_8_event_1, :integer
    add_column :generators, :score_8_event_2, :integer
    add_column :generators, :score_8_event_3, :integer
    add_column :generators, :score_8_event_4, :integer
    add_column :generators, :score_8_event_5, :integer
    add_column :generators, :score_8_event_6, :integer
    add_column :generators, :score_8_event_7, :integer
    add_column :generators, :score_8_event_8, :integer
  end
end
